;; This logfile was generated automatically by `xindy'
;; at 11.04.2011  15:00:44
;; Indexstyle: "/var/folders/AK/AKFRDJbA2Ra1dE+BYvZNkU+++TI/-Tmp-/n1TwJnHNUh", Rawindex: "/var/folders/AK/AKFRDJbA2Ra1dE+BYvZNkU+++TI/-Tmp-/vatSK2IQzH", Output: "DissertationMain.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ë†" -> "R"
Letter-group: "´¼" -> "L"
Letter-group: "2¨—" -> "glsnumbers"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "2¨—" -> "glsnumbers"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´¼" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë†" -> "R"
